server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/world
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 378119898030-ko1oh5jg97dkf0d5auvtet5n3g4c8g5p.apps.googleusercontent.com
            client-secret: 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
          facebook:
            client-id: 465358593799840
            client-secret: a37286e3dae00dcdce628f40dfe363f5
custom:
  oauth2:
    kakao:
      client-id: 1b8ff676ae01724ed77437f98d399543